name: Release

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'yarn'

      - run: yarn install --no-immutable
      - run: yarn test

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply yarn.lock changes

      - run: yarn release

      - name: Publish secondarily to npm
        run: npm publish --access=public --ignore-scripts --@alienfast:registry='https://registry.npmjs.org'
        if: github.ref == 'refs/heads/main'